refactoring testpmd operator to operator-sdk 1.33.0
openshift-kni/example-cnf pull request #57
Opened 2024-02-15 13:49 UTC by capolrik

Sfter Testpmd-lb-operator and cnf-mac-app-operator, here it comes the refactoring of testpmd-operator

2024-02-16 13:51 UTC, ramperher requested changes
Some comments, comparing with https://github.com/openshift-kni/example-cnf/pull/53:

- Include in the README the `operator-sdk` commands executed to create the project structure
- roles/testpmd/vars/main.yml file is missed (it's just an empty file but just to have the same than in testpmd-lb-operator)

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/manager/manager.yaml
> +      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
I'd remove these comments

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/manager/manager.yaml
> +        # TODO(user): For common cases that do not require escalating privileges
I'd remove these comments

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/manager/manager.yaml
> +        # TODO(user): Configure the resources accordingly based on the project requirements.
These comments can be probably removed

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/manager/manager.yaml
> -          startupProbe:
do not remove startupProbe (comment above is not needed)

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/manager/manager.yaml
> -          lifecycle:
do not remove lifecycle

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/manager/manager.yaml
> -          terminationMessagePolicy: FallbackToLogsOnError
do not remove terminationMessagePolicy

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/rbac/kustomization.yaml
> +- auth_proxy_service.yaml
I'd keep these four resources commented

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/rbac/role.yaml
> -      - configmaps
do not delete this, it may be probably needed

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/rbac/role.yaml
> -  - apiGroups:
do not delete all this, they are required

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/rbac/role.yaml
> -# +kubebuilder:scaffold:rules
this line is correctly removed, do not re-include it

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/config/samples/examplecnf_v1_testpmd.yaml
> -  image_testpmd: registry.redhat.io/openshift4/dpdk-base-rhel8:v4.6.3-8
you can keep this spec, it's just a sample

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/roles/testpmd/defaults/main.yml
> +# defaults file for TestPMD
include this line in main.yaml.in at the beginning of the file

2024-02-16 13:51 UTC, ramperher commented on testpmd-operator/roles/testpmd/templates/.placeholder
this can be deleted

2024-02-16 14:04 UTC, capolrik commented on testpmd-operator/Makefile
>  ARCH  = $(shell uname -m | sed 's/x86_64/amd64/')
Are we really supporting arm based system? I can add the line to make it more standard but we don't want to mislead people with false hope.

2024-02-16 14:10 UTC, ramperher commented on testpmd-operator/Makefile
>  ARCH  = $(shell uname -m | sed 's/x86_64/amd64/')
it's just to have the same it's generated from operator-sdk v1.33.0, I'm not sure we support ARM right now, we may probably check in the future if it were used at some point in a test

2024-02-16 14:14 UTC, capolrik commented on testpmd-operator/config/manager/manager.yaml
> -          imagePullPolicy: IfNotPresent
If the image tag is :latest, the imagePullPolicy will be automatically set to Always. If the image tag isn't :latest, the imagePullPolicy will be automatically set to IfNotPresent. So it should not change the behavior. I'll add it to remain consistent with the rest of the code.

2024-02-19 15:53 UTC, capolrik commented on testpmd-operator/config/rbac/role.yaml
>        - watch
Sorry, I thought it was here as reference. I have added it again.

2024-02-19 16:05 UTC, ramperher commented
Change looks good, I'll accept when having a green job with a full example-cnf deployment and testing

2024-02-19 16:59 UTC, ramperher commented
it's weird but it's complaining about this script: https://github.com/dci-labs/example-cnf-config/blob/master/testpmd/hooks/pre-run.yml#L29-L33 , which mainly retrieves the operators that are modified to retrieve the correct SHA. It's like it's not able to see the change in testpmd-operator?

2024-02-22 08:23 UTC, capolrik commented
I fix the dependency issue: the pip install cmd was not run under the correct USER in the dockerfile.

2024-02-22 08:46 UTC, ramperher approved these changes
LGTM, thanks Charles for all the great work here!

Let's wait for PR54 to build the example-cnf component before merging this one, to avoid conflicts: https://github.com/openshift-kni/example-cnf/actions/runs/8001713950

2024-02-22 09:45 UTC, merged